# Generated by Django 4.1 on 2022-09-03 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import messenger.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_ssn', models.CharField(blank=True, max_length=10, null=True)),
                ('user_about', models.CharField(blank=True, max_length=500, null=True)),
                ('user_phone_number', models.CharField(max_length=11)),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to=messenger.models.Account.user_directory_path)),
                ('user_gender', models.CharField(blank=True, choices=[('others', 'Others'), ('female', 'Female'), ('male', 'Male')], max_length=6, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'user', 'user_phone_number')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(blank=True, null=True, upload_to='content/')),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ack', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='messenger.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='messenger.account')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.account')),
            ],
            options={
                'unique_together': {('Account', 'phone_number')},
            },
        ),
    ]
