# Generated by Django 4.1 on 2022-08-20 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_ssn', models.CharField(blank=True, max_length=10, null=True)),
                ('user_about', models.CharField(blank=True, max_length=500, null=True)),
                ('user_phone_number', models.CharField(max_length=11)),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
